# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_auto_20160110_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('college', models.CharField(choices=[('Chr', "Christ's"), ('Chu', 'Churchill'), ('Cla', 'Clare'), ('ClH', 'Clare Hall'), ('Cor', 'Corpus Christi'), ('Dar', 'Darwin'), ('Dow', 'Downing'), ('Emm', 'Emmanuel'), ('Fit', 'Fitzwilliam'), ('Gir', 'Girton'), ('Gon', 'Gonville and Caius'), ('Hom', 'Homerton'), ('Hug', 'Hughes Hall'), ('Jes', 'Jesus'), ('Kin', "King's"), ('Luc', 'Lucy Cavendish'), ('Mag', 'Magdalene'), ('Mur', 'Murray Edwards'), ('New', 'Newnham'), ('Pem', 'Pembroke'), ('Pet', 'Peterhouse'), ('Que', "Queens'"), ('Rob', 'Robinson'), ('Sel', 'Selwyn'), ('Sid', 'Sidney Sussex'), ('SCa', "St Catharine's"), ('SEd', "St Edmund's"), ('SJo', "St John's"), ('Tri', 'Trinity College'), ('TrH', 'Trinity Hall'), ('Wol', 'Wolfson'), ('Una', 'Unaffiliated')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('CS', "Christ's Student"), ('CF', "Christ's First Guest"), ('CG', "Christ's Other Guest"), ('OC', 'Other College'), ('AL', 'Alumni'), ('ST', 'Staff')], max_length=2)),
                ('ticket_crsid', models.CharField(max_length=10)),
                ('ticket_last_name', models.CharField(max_length=100)),
                ('ticket_first_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
