# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
