# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20160111_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
