# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20160111_0019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
