# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20160111_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='charity',
            field=models.IntegerField(default=0),
        ),
    ]
