# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20160112_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ticket_crsid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
